FROM node:16-alpine
WORKDIR '/app'
COPY package.json .
RUN npm config set fetch-retry-mintimeout 20000
RUN npm config set fetch-retry-maxtimeout 120000
RUN npm config rm proxy
RUN npm config rm https-proxy
RUN npm install
COPY . .
CMD ["npm", "run", "start"]
